DISPLAY_CONFIG:
  cache: true
  libraries: true
  strategy_delete: true
  config_reloads: true

# market database querying settings
MARKET_FILTER:
  # date format to present in market filter
  mkt_date_format: "%d %b %y"
  # datetime format used in strategy filter
  strategy_sel_format: "{exec_time:%y-%m-%d %H:%M:%S} {name}"
  
# general table display settings
TABLE:
  # number of rows to display for different tables
  market_rows: 12
  strategy_rows: 12
  runner_rows: 10
  orders_rows: 15
  timings_rows: 15
  
# column mappings of (database column name -> display table column title) for market database table
# N.B. column "market_profit" is not from the database columns but can be added and is calculated from strategy market profit
MARKET_TABLE_COLS:
  market_id: "Market ID"
  market_type: "Market Type"
  market_time: "Market Time"
  venue: "Venue"
  market_profit: "Profit"

# column mappings of (database column name -> label name) for market database table sorting options
MARKET_SORT_OPTIONS:
  market_id: "Market ID"
  market_time: "Market Time"

# column mappings of (database column name -> display table column title) for strategy database table
# -> "n_markets" and "total_profit" are calculated columns, not from DB
STRATEGY_TABLE_COLS:
  strategy_id: "Strategy ID"
  type: "Type"
  name: "Name"
  exec_time: "Execution Time"
  date_added: "Date Added"
  n_markets: "Market Count"
  total_profit: "Total Profit"

# column mappings of (database column name -> display table column title) for market runners database table
# N.B. columns "starting_odds" and "runner_profit" are not from the database columns but can be added -
#      -> "starting_odds" is the odds of the runner at the start of the race
#      -> "runner_profit" is the profit on the runner from the selected strategy
RUNNER_TABLE_COLS:
  runner_id: "Selection ID"
  runner_name: "Name"
  starting_odds: "Starting Odds"
  runner_profit: "Profit"

# mappings from (timing attribute -> display column title)
# timing attributes can be selected from those produced in `mytiming.get_timings.summary()`
TIMINGS_TABLE_COLS:
  function: "Function"
  count: "Count"
  mean: "Mean"
  level: "Level"

# mappings of (timings table column ID -> formatter function)
TIMINGS_TABLE_FORMATTERS:
  mean: "format_timedelta"

# mappings from (session.odr_rd() attributes -> column titles)
ORDER_TABLE_COLS:
  date: "Timestamp"
  trade: "Trade Index"
  side: "Side"
  price: "Price"
  size: "Size"
  m-price: "Matched Price"
  matched: "Matched"
  order-profit: "Order"
  trade-profit: "Trade"
  t-start: "Time to Start"

FORMATTERS_CONFIG:
  # format to display timestamps for columns with "format_datetime" function selected
  dt_format: "%Y-%m-%d %H:%M"
  # format to display time-delta objects from the `mytiming.format_timedelta` function
  td_format: "{d}d {h:02}:{m:02}:{s:02}.{u:06}"
  money_format: "£{value:+.2f}"

# mapping of (database column name -> python formatter function) for market database columns
MARKET_TABLE_FORMATTERS:
  market_time: "format_datetime"
  market_profit: "format_money"


RUNNER_TABLE_FORMATTERS:
  runner_profit: "format_money"

# mapping of (database column name -> python formatter function) for strategy database columns
STRATEGY_TABLE_FORMATTERS:
  exec_time: "format_datetime"
  date_added: "format_datetime"
  total_profit: "format_money"

DB:
  # maximum number of rows to return from a database query
  max_rows: 100

# can use relative paths here
CONFIG_PATHS:
  feature_src: "%USERPROFILE%/OneDrive/betfair/pythonbetfair/configurations/feature_src"
  feature_out: "%USERPROFILE%/OneDrive/betfair/pythonbetfair/configurations/feature_out"
  plot_src: "%USERPROFILE%/OneDrive/betfair/pythonbetfair/configurations/plot_src"
  plot_out: "%USERPROFILE%/OneDrive/betfair/pythonbetfair/configurations/plot_out"
  strategy_dir: "%USERPROFILE%/OneDrive/betfair/pythonbetfair/configurations/strategy_confs"

PLOT_CONFIG:
  # default time offset before start of event for plotting
  default_offset: "00:03:00"
  # number of seconds to plot either side of order update start/end
  order_offset_secs: 2
  # additional seconds to add when computing features for plotting
  cmp_buffer_secs: 10

LAYOUT:
  filter_margins: "mb-1"

DB_CONFIG:
  db_lang: "postgresql"
  db_user: "better"
  db_host: "notrelevant.org.uk"
  db_port: 5432
  db_name: "betting"
  db_engine: "psycopg2"
  cache_root: "%USERPROFILE%\\Documents\\_bf_cache"

CALLBACK_CONFIG:
  # number of milliseconds to call periodic updater
  interval_ms: 1000
