name: poetry_exporter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: generating requirements.txt
      run: |
        ls
        pwd
        poetry export -f requirements.txt -o requirements_TEST.txt --without-hashes
        ls
    
